import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Check if these are named or default exports in your components
import Navbar from "./components/share/Navbar"; // If default export
import Footer from "./components/share/Footer"; // If default export
import FitProvider from "@/context/FitContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#0B1020]">
        <FitProvider>
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />

           <ToastContainer />
        </FitProvider>
      </body>
    </html>
  );
}